### ISSUE TITLE
Bench getting stuck at pos 40/42

### ISSUE THREAD

**Issue by gogamoga1** [syzygy1/Cfish#25] opened 2017-09-05 04:35 UTC
If you type "bench 16 2 13" Cfish will stuck at position 40, though with 1 thread everything OK.

**Comment by syzygy1** [comment] 2017-09-05 07:29
I cannot reproduce the problem on my machine (Linux), but I will have a look later. Does it happen on every run or just once in a while?

**Comment by gogamoga1** [comment] 2017-09-05 09:08
Every time. (https://i.imgur.com/LjzQSn5.gifv)

**Comment by ChessMan3** [comment] 2017-09-05 16:42
Same problem for me:
"bench" - is ok, but "bench 16 2 16" stucks at 40/42 starting after adding **Rewrite benchmark/wide bench coverage** (Restore perft  - is OK)
https://postimg.org/image/qdnvyzdxx/

**Comment by ChessMan3** [comment] 2017-09-05 17:51
I delete patch "Wide bench coverage" and now CFish works normal:
 Left scr - "bench"  Right scr - "bench 16 2 16"  ( & SF "Remove unneeded compile options" without "Wide bench coverage")
https://postimg.org/image/6jk7vts9h/

=====
SRC's: Cfish-master_050917_del_Bench:  http://www67.zippyshare.com/v/wJWb4Oyn/file.html

Stockfish-Rem_comp_opt (and del Bench): http://www67.zippyshare.com/v/dhrpl7te/file.html

**Comment by syzygy1** [comment] 2017-09-05 21:07
Thanks. Should be fixed now.

**Comment by ChessMan3** [comment] 2017-09-05 21:24
Yes, now it's fixed. Thank you!

**Comment by syzygy1** [comment] 2017-09-05 23:29
Excellent!

**Closed by syzygy1** 2017-09-05 23:29 UTC
