### ISSUE TITLE
Cerebellum book support

### ISSUE THREAD

**Issue by ChessMan3** [syzygy1/Cfish#30] opened 2017-11-27 10:57 UTC
Hello! It is not an issue.
I think I can speak on behalf of all the fans of Cfish: could you add support for the Cerebellum book as in Brainfish or ASMfish? I think all Cfish users would like this.

**Comment by syzygy1** [comment] 2017-11-29 00:42
I may have a look when I find some time.

**Comment by ChessMan3** [comment] 2017-12-11 18:08
Thank you for adding Cerebellum book support!
I have some error when compile:

search.c:31:10: fatal error: polybook.h: No such file or directory
 #include "polybook.h"

**Comment by Saugstrahler** [comment] 2017-12-11 18:19
Hi Ronald, I get the same error:

search.c:31:10: fatal error: polybook.h: No such file or directory
 #include "polybook.h"
          ^~~~~~~~~~~~
compilation terminated.

**Comment by syzygy1** [comment] 2017-12-11 20:18
A small oversight :-)

**Comment by CoffeeOne** [comment] 2017-12-11 23:44
Hi,
I tried today with CFish and book Cerebellum_Light_Poly.bin.
Compilation works fine, but book does not work, engine makes no move.
Same books works for me with asmfish.
In comparison to Asmfish, CFish does not have the "Ownbook" UCI option.

**Comment by syzygy1** [comment] 2017-12-12 00:01
It works for me:

$ cfish
setoption name BookFile value /home/ronald/cerebellum/cerebellum.bin
info string Book loaded: /home/ronald/cerebellum/cerebellum.bin
go movetime 1000
bestmove e2e4

**Comment by Alexei1981** [comment] 2017-12-12 07:19
Thanks to Mr. De Man. I compiled this cfish on androids. The book works (only I had to write in the file ucioption.c the path to the folder where the book lies because of the file system features on the android). Now everything works fine!

**Comment by Denzwell** [comment] 2017-12-12 11:55
This version does not work well. The engine stop to move after last book move under windows system.

**Comment by MichaelB7** [comment] 2017-12-12 12:09
Which GUI are you using?  Does the GUI have  a "logging" option you can turn on to help debug? If yes, turn logging on and post the output when it stops playing.   It is working fine under macOS using xBoard with no issues at all.

**Comment by Denzwell** [comment] 2017-12-12 15:44
I use this engine on playchess . I use my ctg book and cerebellum. With brainfish i can use two books.
Cfish can insert debug file for that

**Comment by MichaelB7** [comment] 2017-12-12 15:53
Sorry - I will not be able to help.   MacOS and xboard here. No windows.

**Comment by Denzwell** [comment] 2017-12-12 16:23
On windows
setoption name BookFile value E:\books\cl.bin
info string Book loaded: E:\books\cl.bin
go movetime 1000
<nothing (no moves)>

**Comment by MichaelB7** [comment] 2017-12-12 16:45
Just to confirm , you downloaded the cerebellum book that is in polyglot format? - the old format would not work with Cfish.  Since it is a polyglot book ,any GUI that accepts polyglot books will also be able to read it.   I only ask , because it is unclear in the name of the file that you are trying to load that it is the correct file.

**Comment by Denzwell** [comment] 2017-12-12 16:57
yes i just renamed polyglot cerebellum.bin book to cl.bin. i use the same book with brainfish and it works fine.

**Comment by ChessMan3** [comment] 2017-12-12 17:02
Works fine with Cute Chess 0.9.4, under Windows 10 x64

**Comment by Denzwell** [comment] 2017-12-12 17:07
can you try it with fritz 15 Gui please ?

**Comment by Denzwell** [comment] 2017-12-12 17:27
With Shredder Gui without book, engine works fine. And when you set book it does not work

**Comment by Denzwell** [comment] 2017-12-12 18:04
i allways use Cfish on playchess, this version with polyglot book does not work. i am sure

**Comment by ChessMan3** [comment] 2017-12-12 18:35
Not working in Fritz 15 GUI with book. Without book - works fine.

**Comment by MichaelB7** [comment] 2017-12-12 18:43
You need to get it to work at command line terminal first - can you try another exe and test at command line as you did before ?

**Comment by ChessMan3** [comment] 2017-12-12 19:23
Works fine in Aquarium.

**Comment by CoffeeOne** [comment] 2017-12-12 19:57
yes, easy to reproduce for me, too:
C:\Program Files\cfish>cfish-2017-12-12.exe
Cfish 121217 64 POPCNT NUMA by Syzygy based on Stockfish
setoption name BookFile value C:\Users\Peter\Documents\Cerebellum_light_polyglot\Cerebellum_Light_Poly.bin
info string Book loaded: C:\Users\Peter\Documents\Cerebellum_light_polyglot\Cerebellum_Light_Poly.bin
go movetime 1000
info string Transposition table allocated using large pages.
bestmove e2e4
setoption name Threads value 8
go movetime 1000
=> no answer, also not after 5 minutes

**Comment by CoffeeOne** [comment] 2017-12-12 20:01
Maybe I should add, after go movetime 1000, the engine hangs, I cannot even terminate with the uci command quit.

**Comment by syzygy1** [comment] 2017-12-12 20:07
OK, I have the same problem when I compile for Windows and run it with Wine. I will investigate.

**Comment by syzygy1** [comment] 2017-12-12 20:32
Should be fixed now.

**Comment by CoffeeOne** [comment] 2017-12-12 20:41
Works now for me.
Thank you very much.

**Comment by ChessMan3** [comment] 2017-12-12 20:47
For me too - works fine. (Fritz 15 GUI & Cute Chess)

Thank you!

**Comment by syzygy1** [comment] 2017-12-12 20:57
Is the Ownbook option important?

**Comment by CoffeeOne** [comment] 2017-12-12 21:07
It is conveniant when you want to quickly switch the Cerebellum book on and off, but for me that is not a common use case, so I am neutral about it :)

**Comment by ChessMan3** [comment] 2017-12-12 21:10
For me, this is also not critical.

**Comment by MichaelB7** [comment] 2017-12-12 21:14
Not for me - I never touch it.  But maybe I should be using it more. I’m a little bit Neanderthal and turn the book off and on by making the path incorrect and correct.  Did not realize that  was what the option for - I thought it was for something else.   Not that I know , I would keep it.

**Comment by MichaelB7** [comment] 2017-12-12 21:14
Now that I know...

**Comment by Denzwell** [comment] 2017-12-12 21:47
OK it works now. Thanks you very much syzygy. I Will try it this night on playchess

**Comment by syzygy1** [comment] 2017-12-13 00:16
You're welcome. Let me know if something seems wrong.

I'll probably add Ownbook one of these days.

**Closed** 2018-03-28 21:29 UTC
