### ISSUE TITLE
do_null_move nnue update

### ISSUE THREAD

**Issue by dshawul** [syzygy1/Cfish#171] opened 2020-10-15 17:13 UTC
Not an issue but a suggestion. It seems this part of the code in do_null_move is not needed
```
#ifdef NNUE
  if ((st-1)->accumulator.computedAccumulation)
    st->accumulator = (st-1)->accumulator;
  else
    st->accumulator.computedAccumulation = false;
#endif
```

**Comment by syzygy1** [comment] 2020-10-15 22:47
Hi Daniel. I think it is still needed in very rare cases (because of how dirtyNum == 0 is mishandled in nnue.c).

Ideally this code in do_null() should go because it is inconsistent with how do_move() does _not_ update the accumulator. I think last time I tried removing it was a small speed loss, but after some other changes this may now be different. So time to test again.

**Comment by dshawul** [comment] 2020-10-16 05:56
I will see why it is not making a difference for me.
Another thing is that CFish seems to give different results for NNUE done with and without increment.
```
///if (!update_accumulator(pos))
    refresh_accumulator(pos)
```
Using 1-thread and searching upto depth 28 `go depth 28`, I get different results.
OTOH, the official-stockfish version gives identical results making similar modifications at the start of Transform function.
This maybe due to the incremental update being wrong somewhere.

**Comment by syzygy1** [comment] 2020-10-16 08:22
Do you get the different result after removing those lines from do_null()?

This is because only very rarely nnue_evaluate() is being called after a null move, and things go wrong if the accumulator hasn't been copied. (But now I'm getting confused because even with the current code, it is not always copied because the parent doesn't always have an updated accumulator.)

**Comment by dshawul** [comment] 2020-10-16 11:58
This is without removing those lines in do_null.
I used `commit a9963c6741b26be4de7c120ab565752` and network `nn-baeb9ef2d183.nnue`
Incremental result for `go depth 28` from stat position
```
info depth 28 seldepth 38 multipv 1 score cp 25 nodes 26580917 nps 1093190 hashfull 1000 tbhits 0 time 24315 pv e2e4 e7e5 g1f3 b8c6 f1b5 g8f6 e1g1 f8c5 c2c3 c5b6 d2d4 e8g8 f1e1 d7d6 h2h3 c6e7 b5d3 e7g6 c1e3 c7c6 c3c4 e5d4 e3d4 b6d4 f3d4 g8h8
```
Without incremental update
```
info depth 28 seldepth 38 multipv 1 score cp 34 nodes 23168729 nps 899931 hashfull 1000 tbhits 0 time 25745 pv e2e4 e7e5 g1f3 b8c6 d2d4 e5d4 f3d4 g8f6 d4c6 b7c6 f1d3 d7d5 e4e5 f6d7 e1g1 d7c5 f2f4 g7g6 c1e3 f8e7 d3e2 c5e6 g1h1 e8g8 f4f5 g6f5 f1f5
```
Btw result was the same upto depth 27.

**Comment by syzygy1** [comment] 2020-10-16 12:29
Ah, ok. Well, those lines are still almost redundant but it is a bit tricky.

I think the discrepancy you noticed must be related to null moves. I could not reproduce it, but I tried with the new network. I think it is time to set dirtyNum to 0 in do_null()...

**Comment by dshawul** [comment] 2020-10-16 12:52
Indeed, switching to latest version `a1bfa179cf4e1147381e` and network `nn-04cf2b4ed1da.nnue`, I get same results even upto
depth 30. There is only one commit difference between the two tests.

**Comment by syzygy1** [comment] 2020-10-25 19:46
Bugs (in both Cfish and Stockfish) have been fixed with the incremental NNUE patch.
Thanks for noticing the node count discrepancy!

**Closed by syzygy1** 2020-10-25 19:46 UTC
